[project]
name = "sam-unisex-salon"
version = "1.0.0"
description = "Sam Unisex Salon - Premium Hair Salon Management System"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.7",
    "psycopg2-binary>=2.9.9",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
]
